# =====================
# Python 3.9.16 core image
# ---------------------

FROM python:3.9.16

# =====================
# Basic enviroment setup
# ---------------------

# Set default environment
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    apt-utils \
    curl \
    locales \
    nano \
    ssh \
    sudo \
    bash \
    git \
    make \
    gcc \
 && rm -rf /var/lib/apt/lists/*

# =====================
# User stuff
# ---------------------

# https://wiki.debian.org/Locale#Manually
RUN sed -i "s/# en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen \
  && locale-gen
ENV LANG=en_US.UTF-8
ENV SHELL=/bin/bash

RUN adduser --gecos '' --disabled-password coder \
  && echo "coder:admin-coder" | chpasswd \
  # && echo "coder ALL=(ALL) ALL" >> /etc/sudoers.d/sudouser \
  && usermod -s /bin/bash coder

# ==========================================
# Project-specific installation instruction
# ------------------------------------------

COPY bash.bashrc /etc
RUN chmod +x /etc/bash.bashrc
ENV BUILD_ENVIRONMENT="development"
ENV XDG_CACHE_HOME="/opt/dev/cache"
WORKDIR /home/coder/autogoal

# Make RUN commands use the autogoal environment
COPY makefile /home/coder/autogoal/

# Setup poetry configuration
RUN pip install -U pip setuptools
RUN pip install poetry==1.8.4
RUN poetry config virtualenvs.create false

SHELL ["/bin/bash", "-c"]
RUN mkdir -p /home/coder/autogoal/data && rm -rf /home/coder/autogoal/storage && chown -R coder:coder /home/coder/autogoal

# Set permissions for important directories
RUN chown -R coder /home/coder
RUN chown -R coder /opt/dev/cache

# Copy code-base for autogoal-core
COPY autogoal/ /home/coder/autogoal/autogoal

# Copy code-base for autogoal-contrib
COPY autogoal-contrib/ /home/coder/autogoal/autogoal-contrib

# Copy code-base for autogoal-remote
COPY autogoal-remote/ /home/coder/autogoal/autogoal-remote

# Copy code-base for autogoal-remote
COPY scripts/ /home/coder/autogoal/scripts

# Install autogoal core
COPY dockerfiles/install-package.sh /home/coder/autogoal/install-package.sh 
RUN sudo chmod +x install-package.sh && sudo ./install-package.sh core

# Allow 'coder' to use sudo without a password
RUN echo "coder ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/coder && sudo chmod 0440 /etc/sudoers.d/coder

# Finally switch to coder so at runtime the user must supply the password for sudo:
USER coder
VOLUME /home/coder/autogoal

CMD ["/bin/bash"]