name: Build and Push to Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push base image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: autogoal/autogoal:core
          context: "."
          file: "dockerfiles/core/dockerfile"

      - name: Build and Push Image with all contribs
        run: bash ./scripts/generate_full_image.sh -p

      # - name: Generate Docker images for each contrib
      #   run: bash ./scripts/generate_contrib_images.sh -p
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
